version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: facework-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: facework
    volumes:
      - mongodb_data:/data/db
    networks:
      - facework-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: facework-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=mongodb://mongodb:27017/facework
      - JWT_SECRET=dev_jwt_secret_key_32_characters_min
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - facework-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: facework-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    depends_on:
      - backend
    networks:
      - facework-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  facework-network:
    driver: bridge
